import Navbar from "@/components/Navbar";
import "./globals.css";
import { Providers } from "@/utils/Providers";
export const metadata = {
  title: "TravelBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Providers>
          <Navbar/>
          {children}</Providers>
      </body>
    </html>
  );
}
